### ISSUE TITLE
Add Channel Poll Event's & Poll-Parser

### ISSUE THREAD

**Issue by Breitling1992** [Luzifer/twitch-bot#45]
It often happens that the PubSub-Socket break, in this case people can't see active poll's. 
It would be a helpful enhancement, to be able to post the current state of an active poll and the result, after the poll ends. With this feature, chatter could vote with the /vote X command, instead of reloading the page. 
Therefor 2 new events are necessary and some templates: 

New Events:
- [channel.poll.begin](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelpollbegin) 
- [channel.poll.end](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelpollend)

Templating: 
- [Poll Parser](https://dev.twitch.tv/docs/api/polls/) to get => pollTitle, vote1Title, vote1Count, [...], vote5Count

**Comment by Luzifer** [comment]
> With this feature, chatter could vote with the /vote X command, instead of reloading the page.

Sadly this isn't true in the most cases: When the raid isn't available to the client `/vote X` doesn't work either…

**Comment by Luzifer** [comment]
Implemented
- `poll_begin`, `poll_end`, `poll_progress` events: 04648a2
- `lastPoll` function: 8ad973a
